apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: pyspark-notebook-service
spec:
  type: LoadBalancer
  selector:
    app: pyspark-notebook
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: spark-driver
spec:
  selector:
    app: pyspark-notebook
  ports:
    - protocol: TCP
      port: 29413
  clusterIP: None
